apiVersion: v1
kind: Service
metadata:
  name: kipoi-backend-keras1-lb
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: kipoi-backend-keras1